### ISSUE TITLE
[BUG] Ubuntu 20.04 can not successfully run, error in `from rtx import RTX1`

### ISSUE THREAD

**Issue by SnallQiu** [kyegomez/RT-X#6]
Thanks for the reproduction with RT-X in torch version. 
I'm trying to run the rtx1_example.py in Ubuntu 20.04 with python3.8, where the virtual environment is newly created , and `pip install torch rtx-torch`
the running error is following:
```
Traceback (most recent call last):
  File "rtx1_example.py", line 2, in <module>
    from rtx.rtx1 import RTX1
  File "/home/ustc/qiuqc/grasp/open-x/RT-X/rtx/__init__.py", line 1, in <module>
    from rtx.rtx2 import RTX2
  File "/home/ustc/qiuqc/grasp/open-x/RT-X/rtx/rtx2.py", line 4, in <module>
    from zeta.nn.architecture import (
  File "/home/ustc/venv/open-x-torch/lib/python3.8/site-packages/zeta/__init__.py", line 22, in <module>
    from zeta import tokenizers
  File "/home/ustc/venv/open-x-torch/lib/python3.8/site-packages/zeta/tokenizers/__init__.py", line 5, in <module>
    from zeta.tokenizers.tiktoken import TikToken
  File "/home/ustc/venv/open-x-torch/lib/python3.8/site-packages/zeta/tokenizers/tiktoken.py", line 8, in <module>
    from zeta.tokenizers.base import BaseTokenizer
  File "/home/ustc/venv/open-x-torch/lib/python3.8/site-packages/zeta/tokenizers/base.py", line 9, in <module>
    class BaseTokenizer(ABC):
  File "/home/ustc/venv/open-x-torch/lib/python3.8/site-packages/zeta/tokenizers/base.py", line 12, in BaseTokenizer
    stop_sequences: list[str] = field(
TypeError: 'type' object is not subscriptable
```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/RT-X/issues/6">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/RT-X/issues/6/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/RT-X/issues/6/pledge.svg">
</picture>
</a>

**Comment by kyegomez** [comment]
@SnallQiu Can you try again please!
