### ISSUE TITLE
[BUG] Unable to run rt2x example script when running from source

### ISSUE THREAD

**Issue by sebbyjp** [kyegomez/RT-X#8]
**Describe the bug**

**To Reproduce**
```
% pip install rtx-torch
% python rtx2_example.py 
```

Output:
```
(rtx1) sebastianperalta@Sebastians-MacBook-Pro RT-X % python rtx2_example.py           
Traceback (most recent call last):
  File "/Users/sebastianperalta/simply/dev/simply-mono/RT-X/rtx2_example.py", line 2, in <module>
    from rtx import RTX2
  File "/Users/sebastianperalta/simply/dev/simply-mono/RT-X/rtx/__init__.py", line 1, in <module>
    from rtx.rtx2 import RTX2
  File "/Users/sebastianperalta/simply/dev/simply-mono/RT-X/rtx/rtx2.py", line 4, in <module>
    from zeta.nn.architecture import (
  File "/Users/sebastianperalta/simply/dev/simply-mono/venvs/rtx1/lib/python3.11/site-packages/zeta/__init__.py", line 40, in <module>
    from zeta.logo import print_colored_logo
  File "/Users/sebastianperalta/simply/dev/simply-mono/venvs/rtx1/lib/python3.11/site-packages/zeta/logo.py", line 1, in <module>
    from rich import print as rich_print
ModuleNotFoundError: No module named 'rich'
```

**Additional context**
python3.11
MacOS

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/RT-X/issues/8">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/RT-X/issues/8/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/RT-X/issues/8/pledge.svg">
</picture>
</a>

**Comment by kyegomez** [comment]
@sebbyjp I have justed tried to fix this error, let me know if it works!
